#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()

result = re.match('^([a-z]+)\/([A-Z]+)-([0-9]+)#([a-z0-9-]+)$', branch)

task_type = result.group(1)

with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    pattern = "^%s(\([a-z]+\)):\s[a-z0-9.\s,-]+$" % (task_type)
    result = re.match(pattern, content)
    contract = "<type>(<scope>): <subject>"
    example = "feat(login): created screen"
    if (result == None):
        print "commit-msg: ERROR! The commit message must adhere to this contract:\nContract: %s\nPattern: %s\nExample: %s" % (contract, pattern, example)
        sys.exit(1)
    else:
        print "commit-msg: SUCESS!"
        sys.exit(0)