#!/usr/bin/sh

# Text decoration variables
RED_BOLD='\033[0;31;1m'
GREEN_BOLD='\033[0;32;1m'
YELLOW_BOLD='\033[0;33;1m'
BOLD='\033[1m'
NORMAL='\033[0m'

# Get the name of the current branch
LOCAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

TYPE_PATTERN="(feat|fix|docs|style|refactor|test)"
CARD_NAME_PATTERN="([A-Z]+)"
CARD_NUMBER_PATTERN="([0-9]+)"
SUBJECT_PATTERN="([a-z0-9-]+)"

PATTERN="^${TYPE_PATTERN}\/${CARD_NAME_PATTERN}-${CARD_NUMBER_PATTERN}#${SUBJECT_PATTERN}"

echo -e "${BOLD}pre-commit: Testing for branch name error...${NORMAL}"
if ! [[ $LOCAL_BRANCH =~ $PATTERN ]]
then
    echo -e "${RED_BOLD}pre-commit: The branch does not have a valid name${NORMAL}"
    echo -e "The branch must have a name that follows the format <type>/<CARD-NAME>-<card-number>#<subject>"
    echo -e "Example: feat/CARD-0000#subject"
    echo -e "${RED_BOLD}pre-commit: Aborting commit due to branch name error${NORMAL}"
    exit 1
else
    echo -e "${GREEN_BOLD}pre-commit: The branch has a valid name${NORMAL}"
fi

# Check if this is initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    HASH_COMMIT=HEAD
else
    # Represents an empty commit
    HASH_COMMIT=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
echo -e "${BOLD}pre-commit: Testing for whitespace errors...${NORMAL}"
if ! git diff-index --check --cached $HASH_COMMIT
then
    echo -e "${RED_BOLD}pre-commit: Aborting commit due to whitespace errors${NORMAL}"
    exit 1
else
    echo -e "${GREEN_BOLD}pre-commit: No whitespace errors${NORMAL}"
    exit 0
fi