#!/bin/sh

# Get the name of the local branch
local_branch=$(git rev-parse --abbrev-ref HEAD)

# Determines the regex pattern to follow
valid_branch_regex="^(feat|fix|docs|style|refactor|test|cherry-pick)\/([A-Z]+-[0-9]+)#[a-z0-9-]+$"

if ! [[ $local_branch =~ $valid_branch_regex ]]
then
	echo "pre-commit: There is something wrong with your branch name"
	echo "Branch names must adhere to this contract:"
	echo $valid_branch_regex.
	echo "Your commit will be rejected."
	echo "You should rename your branch to a valid name and try again."
	exit 1
fi

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
echo "pre-commit: Testing for whitespace errors..."
if ! git diff-index --check --cached $against
then
    echo "pre-commit: Aborting commit due to whitespace errors"
    exit 1
else
    echo "pre-commit: No whitespace errors :)"
	exit 0
fi